### ISSUE TITLE
First ever Woodpecker community call

### ISSUE THREAD

**Issue by laszlocph** [woodpecker-ci/woodpecker#198]
# [Date](https://www.timeanddate.com/worldclock/converter.html?iso=20220307T210000&p1=tz_gmt&p2=tz_cet&p3=tz_et&p4=tz_aet)
21:00 UTC - [What time is that where you live? Check here!](https://www.timeanddate.com/worldclock/converter.html?iso=20220307T210000&p1=tz_gmt&p2=tz_cet&p3=tz_et&p4=tz_aet)

# [Join](https://public.senfcall.de/woodpecker-ci)
https://public.senfcall.de/woodpecker-ci

# Agenda
- who are we? meet and greet every participant
- short history of woodpecker
- long term plan (current vision of owners) for woodpecker
- discuss / ask for general community opinion regarding:
  - adding https://github.com/woodpecker-ci/woodpecker/issues/84  to have an overview of the community growth
  - docker independent server (move backend related code to agent => for example remove things like networks, volumes from pipeline config)
  - first add / support for settings in repo settings UI per user and only if necessary add them as global options via env vars as quite some community members are hosting WP as "large" deployment with many independent users
  - #602 (how urgent would this be needed?) 
  - do we need to change any general governance related things?

# TODO
- [x] Invite past contributors
- [x] Invite Discord members
- [x] Make it public
- [x] Write up agenda and goals

**Comment by laszlocph** [comment]
https://github.com/go-gitea/gitea/issues/5572
https://github.com/go-gitea/gitea/issues/5572

**Comment by laszlocph** [comment]
Agenda proposal:

- who are we? meet and greet every participant
- short history of woodpecker
- who has experience running/participating in successful open-source communities?
- governance proposal
- interim governance
- volunteers for owning gitea issues
- volunteers for owning arm issues
- ?

**Comment by 6543** [comment]
https://framadate.org/ix3i3pxHSfgJ78sCkfjmsmKn/admin

@woodpecker-ci/advisors

**Comment by davidak** [comment]
Good you noticed yourself. You should remove the entry from history too!

I'm also interested in the project and might show up.

**Comment by 6543** [comment]
meeting: https://public.senfcall.de/woodpecker-ci
time: **21:00 UTC ( 22:00 CET )**

**Comment by 6543** [comment]
Responce:
 - more duplication removal
 - Telemetry is ok -> opt out with environment var ...
 - compile "step" for dynamic pipeline
 - feature: glob filter for images that are allowed
 - config should be yaml compliant
 - login -> summary issue
 - project board -> priorize
 - important -> streamline terms in code (reduce structs) -> issues!!!

**Comment by 6543** [comment]
official guid -> how to setup registroy -> or awesome list

**Comment by 6543** [comment]
"cookboock docs"

**Comment by 6543** [comment]
meeting slides: https://codeberg.org/attachments/23c966d3-e34e-43f5-844f-0d2df8b5cd93

**Comment by alexmt** [comment]
Any plans to have a meeting again? If yes, I would be first in line to join :)

**Comment by 6543** [comment]
-> #1730
