### ISSUE TITLE
Fix version check

### ISSUE THREAD

**Issue by qwerty287** [woodpecker-ci/woodpecker#2748]
### Component

web-ui

### Describe the bug

@anbraten 

- [x] This does not work on light theme (fix: #2765):
    ![](https://github.com/woodpecker-ci/woodpecker/assets/80460567/df78e937-a2e9-44cd-b824-82b99872a0f0)
    Looks like the SVG has a hardcoded backend color which if `fff`
- [x] And if you're on next if there's an update it links to a not existing release page. (see https://ci.woodpecker-ci.org/admin#info), e.g. https://github.com/woodpecker-ci/woodpecker/releases/tag/next-fe48928 #2871 
- [ ] if our CI does not update the docs because of `path` filters the version.json file is not updated.
- [ ] if only `docs` wf runs the version.json is updated even though there's no new docker image
- [x] RC versions are never respected #2871 
    ![](https://github.com/woodpecker-ci/woodpecker/assets/80460567/dbc33bc8-20e4-43c2-bb8b-377e07debc40)

### System Info

```shell
after #2722
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).

**Comment by xoxys** [comment]
Please add an option to disable the check. It creatse noise in cases where deployments and updates are automated anyway.

**Comment by xoxys** [comment]
I've added the icon color fix to https://github.com/woodpecker-ci/woodpecker/pull/2765

**Comment by zc-devs** [comment]
> option to disable the check

On the other hand, as it's implemented on client side, we can "disable" it via Content Security Policy.

**Comment by xoxys** [comment]
You can also block outgoing traffic to this route, also custom CSS can be used to just remove the red indicator from the UI. However, that are just hacks and I really don't like to enforce this for everyone... It can be enabled by default but users should not be enforced to use hacks to get rid of it.

**Comment by zc-devs** [comment]
I agree with you and can come up with cases when it's useless :)

---

I just want to note, that CSP doesn't involve user interaction, it is set up on the server.
For example (HAProxy):
```
backend woodpecker
    server         woopeck_srv        192.168.10.10:8080
    http-response  add-header       Content-Security-Policy "default-src 'self'; base-uri 'self'; connect-src 'self'; form-action 'self'; frame-ancestors 'none'"
```
`connect-src 'self'` will block connections from JS to anything, except domain, where your woodpecker is hosted.

**Comment by xoxys** [comment]
Blocking traffic on the server through a firewall, network policy on kubernetes or even custom css which is applied on the server deployment as well also don't require user-interaction.

**Comment by zc-devs** [comment]
Yes, but this is client-side check (as implemented now). So, blocking traffic on server won't work :) Custom CSS should work.

**Comment by xoxys** [comment]
Oh yes now I get your point 🙈

**Comment by zc-devs** [comment]
> option to disable the check

#3040
