### ISSUE TITLE
Enhance config linter

### ISSUE THREAD

**Issue by anbraten** [woodpecker-ci/woodpecker#276]
Woodpecker should properly lint and evaluate the ci file/files and show errors with the specific position to users. 

- [x] return linter errors to UI #460
- [x] add way to let linter return warnings like deprecations / bad habits #922
- [x] lint every pipeline config before executing with json schema (currently only some checks)
- [x] add cli command to execute pipeline linter (currently only json schema check)
- [ ] add endpoint to be able to paste in config code and highlight the result in UI #892
- [ ] show json schema errors of executed pipelines in UI by highlighting the wrong part
- [x] allow to lint using multiple workflow files (needed for #2685)

With #89 we could show the errors at their specific position in the config. Maybe somehow like:

![Screenshot from 2021-08-24 00-53-36](https://user-images.githubusercontent.com/6918444/130529580-a578c52c-4128-415f-91ae-7889cf053d8a.png)

**Comment by 6543** [comment]
@anbraten would it help if we just add an endpoint, where you can send config in body and get lint error in return?

**Comment by anbraten** [comment]
There are a few things I had in mind:

- lint every pipeline config before executing with json schema (currently only some checks)
- show json schema errors of executed pipelines in UI by highlighting the wrong part
- add endpoint to be able to paste in config code and highlight the result in UI
- add cli command to execute pipeline linter (currently only json schema check)
- add way to let linter return warnings like deprecations / bad habits

**Comment by x80486** [comment]
> @anbraten would it help if we just add an endpoint, where you can send config in body and get lint error in return?

I think along with some integration in the UI will do it. It's always great to double check the config before pushing any related changes.

**Comment by 6543** [comment]
https://www.npmjs.com/package/jsonschema
or
https://www.npmjs.com/package/ajv
?
