### ISSUE TITLE
Add "meta" workflow for matrix workflows, to have easy status check rules

### ISSUE THREAD

**Issue by xoxys** [woodpecker-ci/woodpecker#2886]
### Component

server

### Describe the bug

With v2.0 the behavior of matrix workflows has changes. Instead of a single `ci/woodpecker/pr/test` check, multiple `ci/woodpecker/pr/test/<NUMBER>` checks are reported now, one for each item in the matrix. As a result, existing rules for required status checks in the forge are broken, which also affects all automations bases on successful status checks.

![image](https://github.com/woodpecker-ci/woodpecker/assets/3391958/6862da38-44fa-4e0e-bd7d-2aff40c8d2cb)

IMO there should be a single check again instead of dedicated checks for each matrix element. A matrix can be dynamic (frequent changes to the number of elements) which makes it nearly impossible to enforce it.

### System Info

```shell
{"source":"https://github.com/woodpecker-ci/woodpecker","version":"next-111a0b4ea5"}
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).

**Comment by xoxys** [comment]
I guess related PR is https://github.com/woodpecker-ci/woodpecker/pull/2695

**Comment by xoxys** [comment]
Understandable, but IMO this really makes it quite useless if you need to enforce those checks to pass. While I build and test tool today for python3.10, 3.11 and 3.12 I might add python-nightly tomorrow and remove 3.10 a few days later. Adjusting the forge settings every time the matrix changes doesn't scale at least not for me.

**Comment by 6543** [comment]
I propose (if not already done so) a "meta" pipeline that collect all matrix status and if one fails it is failed, else it is passed.

this is reported back so you can set that one as required.

for gitea you can just specify a regex in recent versions :)
