### ISSUE TITLE
Buildin Environment variable which hold the milestone

### ISSUE THREAD

**Issue by 6543** [woodpecker-ci/woodpecker#3285]
### Clear and concise description of the problem

I need to check if a PR has a milestone set.

### Suggested solution

Best would be to have an environment variable which holds the name of the milestone.

### Alternative

I could use a command line tool or even curl to ask my forge. However this creates extra stuff to maintain, e. g. how login to the forge? On the other hand Woodpecker fetches already so many stuff from the forge, why not just provide that information too?

### Validations

- [x] Checked that the feature isn't part of the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [x] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/main/CONTRIBUTING.md).
- [x] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [x] Check that there isn't already an [issue](https://github.com/woodpecker-ci/woodpecker/issues) that request the same feature to avoid creating a duplicate.

---
*Sponsored by Kithara Software GmbH*
