### ISSUE TITLE
Move woodpecker-plugins to single forge

### ISSUE THREAD

**Issue by anbraten** [woodpecker-ci/woodpecker#3530]
We currently have plugins at:

- 11: https://github.com/orgs/woodpecker-ci/repositories?language=&q=plugin&sort=&type=all
- 16: https://codeberg.org/woodpecker-plugins

To simplify development some maintainers suggested to move all to one place.

# Tasks

- [ ] move plugins to decided forge
- [ ] update plugin index to point to new plugins locations

Currently most maintainers seem to be liking the idea to move plugins to codeberg (which would somehow support both forges, core here at github, plugins at codeberg).

**Comment by anbraten** [comment]
Move to github 👍🏾

**Comment by anbraten** [comment]
Move to codeberg 👍🏾

**Comment by anbraten** [comment]
Don't care / plugins can stay at both forges 👍🏾

**Comment by anbraten** [comment]
Okay, so we will move plugins (apart from plugin-git) to codeberg now:

- [ ] https://github.com/woodpecker-ci/plugin-ready-release-go
- [ ] https://github.com/woodpecker-ci/plugin-github-release
- [ ] https://github.com/woodpecker-ci/plugin-surge-preview
- [ ] https://github.com/woodpecker-ci/plugin-deployments
- [ ] https://github.com/woodpecker-ci/plugin-codecov
- [ ] https://github.com/woodpecker-ci/plugin-s3
- [ ] https://github.com/woodpecker-ci/plugin-extend-env
- [ ] https://github.com/woodpecker-ci/plugin-prettier
- [ ] https://github.com/woodpecker-ci/plugin-kaniko

**Comment by anbraten** [comment]
Good point. Will hopefully be included in next Gitea release. So we still have to wait for forgejo and codeberg to update respectively.

**Comment by pat-s** [comment]
RCs for 1.22 are out, so we can expect this to be unblocked within the next couple of weeks.
