### ISSUE TITLE
Reference secret values from Kubernetes secrets

### ISSUE THREAD

**Issue by dominic-p** [woodpecker-ci/woodpecker#3582]
### Clear and concise description of the problem

It would be nice to be able to leverage [Kubernetes native Secrets](https://kubernetes.io/docs/concepts/configuration/secret/) inside of Woodpecker pipelines.

### Suggested solution

I'm imagining a workflow definition that looks like this:

```yaml
steps:
  - name: docker
    image: docker
    commands:
      - echo $docker_username
      - echo $DOCKER_PASSWORD
    secrets:
    - docker_username
    - name: DOCKER_PASSWORD
      kubernetesRef:
        name: my-docker-secret
        key: password
```

So, the `docker_username` secret would be referenced as it normally is today. The value for the `DOCKER_PASSWORD` secret would come from a Kubernetes Secret called `my-docker-secret` that is defined in the same namespace that pipeline runs. That secret is expected to have a key named `password` that contains the value that we want to use for the secret.

This is loosely based on [the way Drone does it](https://blog.drone.io/drone-kubernetes-secrets/) and the way that Kubernetes allows you to reference secrets for env variables.

The exact syntax is, of course, flexible, but the idea is to allow for other external secret providers as well (see #929).

### Alternative

Right now, it seems like the only way to [define secrets](https://woodpecker-ci.org/docs/usage/secrets#adding-secrets) is via the UI or the CLI. This works, but this isn't ideal if you already have the secretes defined in your cluster.

Another alternative would be to store the information in [global env variables](https://woodpecker-ci.org/docs/usage/environment#global-environment-variables), but that doesn't seem ideal from a security standpoint.

Another option would be to expand the Kubernetes backend [volume mounting logic](https://woodpecker-ci.org/docs/administration/backends/kubernetes#volumes) to allow mounting Secrets in addition to PVs.

### Additional context

This is part of my ongoing effort to get a container build system (specifically buildah) to run on Woodpecker on a CRI-O based Kubernetes cluster. I currently have it up and working, but I need a way to pass registry credentials to it. Otherwise, I can build images, but I can't push them to my repo when I'm done.

There may be a simpler way to do this that I'm just missing at the moment.

### Validations

- [X] Checked that the feature isn't part of the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't already an [issue](https://github.com/woodpecker-ci/woodpecker/issues) that request the same feature to avoid creating a duplicate.

**Comment by everflux** [comment]
An alternative would be to have all implementation specific parts in 'backend_options' - 'kubernetes'

**Comment by dominic-p** [comment]
Yes, that makes sense as well. We could have an implementation like this:

```yaml
steps:
  - name: test
    image: alpine
    commands:
      - echo $my_password
    backend_options:
      kubernetes:
        secrets:
          - name: my_password
            secretRef: my-top-secret-password
            key: password
```

**Comment by zc-devs** [comment]
As I understand FR:
As Admin I want to let users to use (refer to) predefined (existing) Kubernetes secrets in their pipelines.
Am I right?

---

> store the information in [global env variables](https://woodpecker-ci.org/docs/usage/environment#global-environment-variables), but that doesn't seem ideal from a security standpoint

There are global and org secrets.

>  I can't push them to my repo when I'm done.

You can use WP secrets :)

> allow for other external secret providers as well (see https://github.com/woodpecker-ci/woodpecker/issues/929)

This is another thing. At least from implementation point of view.

**Comment by dominic-p** [comment]
Thanks for the explanation. That makes a lot of sense. Keeping it with the other Kubernetes backend options seems like it would definitely be the path of least resistance.

Yes, we could support annotations like this maybe:

```yaml
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: my-pipeline-secret
  annotations:
    woodpecker-ci.org/org-access: "my-org,another-org"
    woodpecker-ci.org/repo-access: "my-repo,another-one"
data:
  password: d29vZHBlY2tlciByb2NrcyE=
```

**Comment by zc-devs** [comment]
To be done:

- [ ] Map an entire secret to environment ([Configure all key-value pairs in a Secret as container environment variables](https://kubernetes.io/docs/tasks/inject-data-application/distribute-credentials-secure/#configure-all-key-value-pairs-in-a-secret-as-container-environment-variables), #3655)
- [ ] Allow to [select keys](https://github.com/woodpecker-ci/woodpecker/issues/3582#issuecomment-2032570971) and map them to [alternate names](https://woodpecker-ci.org/docs/2.3/usage/secrets#alternate-names) ([Define container environment variables using Secret data](https://kubernetes.io/docs/tasks/inject-data-application/distribute-credentials-secure/#define-container-environment-variables-using-secret-data))
- [ ] Mount `.dockerconfigjson` secrets to a file ([Create a Pod that has access to the secret data through a Volume](https://kubernetes.io/docs/tasks/inject-data-application/distribute-credentials-secure/#create-a-pod-that-has-access-to-the-secret-data-through-a-volume), https://github.com/woodpecker-ci/woodpecker/pull/3655#issuecomment-2096671481)
- [ ] Implement access controls (https://github.com/woodpecker-ci/woodpecker/issues/3582#issuecomment-2033256484)
- [ ] Implement secret masking (https://github.com/woodpecker-ci/woodpecker/pull/3655#issuecomment-2081388545)

**Comment by zc-devs** [comment]
Having [last updates](https://github.com/woodpecker-ci/woodpecker/pull/3655#issuecomment-2096671481), syntax below came up in my mind.

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: aws
  namespace: woodpecker
data:
  key-id: N0lrZHNzb0xleGFtcGxlNkpJVnZDRXE=
  access-key: TXk0WE5BYXNleGFtcGxldXRKRHNUWHc=
type: Opaque
```

1. Map an entire secret to the environment:
```yaml
backend_options:
  kubernetes:
    secrets:
      - name: aws
```

2. Select a key:
```yaml
backend_options:
  kubernetes:
    secrets:
      - name: aws
        key: access-key
```

3. Map to an alternate name:
```yaml
backend_options:
  kubernetes:
    secrets:
      - name: aws
        key: key-id
        target:
          env: AWS_ACCESS_KEY_ID
      - name: aws
        key: access-key
        target:
          env: AWS_SECRET_ACCESS_KEY
```

4. Mount as a file:
```yaml
apiVersion: v1
type: kubernetes.io/dockerconfigjson
kind: Secret
metadata:
  name: reg-cred
  namespace: woodpcker
data:
  .dockerconfigjson: <base64 encoded JSON auth file here>
```
```yaml
backend_options:
  kubernetes:
    secrets:
      - name: reg-cred
        key: ".dockerconfigjson"
        target:
          file: "~/.docker/config.json"
```

What do you think?

**Comment by dominic-p** [comment]
I love it. This syntax seems perfect to me.

**Comment by meln5674** [comment]
Being able to do the same things with ConfigMap's would be super swell for things like certificate bundles and site-specific config files that don't belong in git, and the logic should be nearly copy-paste.

**Comment by zc-devs** [comment]
A little bit of clarity here from me.
I've been not using Woodpecker since a while. Therefore there won't be any changes from me, sorry.
So, feel free to write the docs, continue the work, close the issue, whatever.

**Comment by dominic-p** [comment]
I'm happy to contribute to the docs or test things, but my golang understanding is not quite there to help with the coding. I really appreciate all of the help you give me in getting this setup working, @zc-devs. It has been really nice to have a build system that works so smoothly because of your contributions!
