### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by anbraten** [woodpecker-ci/woodpecker#869]
This is a general roadmap for the project covering the most requested epics. They are sorted in some kind of priority (considered by maintainers), but this is not forced.

> Keep in mind Woodpecker has no scheduled releases as it is a OSS project done by volunteers. 

# Roadmap
- [ ] Refactoring of drone 0.8 code
  - [ ] Improve pipeline config compiling #802 
  - [ ] Rename some models / properties #745 
- [ ] Add support for Kubernetes backend #9 #552  #784 
- [ ] Support when filters on root level #283 #770 
- [ ] Add more pipeline events 
  - [ ] PR close #286
  - [ ] Release #764  
- [ ] Support manually triggering a pipeline #83 #240 
- [ ] Add support for HA setup #742

**Comment by anbraten** [comment]
As 1.0 was released now this is my plan for issues I want to work on next:
- [ ] #286 
- [ ] #764 
- [ ] #1572, #276, #922
- [ ] maybe #267 
- [ ] #138
- [ ] some kind of advanced pipeline config maybe by sth like #1400 #1089 
- [ ] think about caching
